/* Storage-independent, versioned public catalog repository. No processing math. */
(function(root){'use strict';
 const PAGE_SIZE=24,MAX_BYTES=4*1024*1024;
 const localized=(value,lang='en')=>value?.[lang]||value?.en||value?.ru||Object.values(value||{})[0]||'';
 const publicPath=p=>typeof p==='string'&&/^\/library\/[a-zA-Z0-9_./-]+$/.test(p)&&!p.includes('..')&&!p.includes('//');
 async function fetchBytes(url,limit=MAX_BYTES){if(!publicPath(url))throw Error('INVALID_ASSET_URL');const response=await fetch(url,{signal:AbortSignal.timeout(20000),cache:'no-cache'});if(!response.ok)throw Error('ASSET_HTTP_'+response.status);if(Number(response.headers.get('content-length'))>limit)throw Error('ASSET_TOO_LARGE');const reader=response.body.getReader(),chunks=[];let size=0;try{while(true){const {done,value}=await reader.read();if(done)break;size+=value.length;if(size>limit)throw Error('ASSET_TOO_LARGE');chunks.push(value);}}finally{await reader.cancel();}const bytes=new Uint8Array(size);let offset=0;for(const chunk of chunks){bytes.set(chunk,offset);offset+=chunk.length;}return {bytes,type:response.headers.get('content-type')?.split(';')[0]};}
 async function fetchJSON(url){const {bytes}=await fetchBytes(url);return JSON.parse(new TextDecoder().decode(bytes));}
 const validTitle=value=>value&&typeof value==='object'&&!Array.isArray(value)&&Object.values(value).some(v=>typeof v==='string'&&v.trim())&&Object.values(value).every(v=>typeof v==='string');
 function validateManifest(data){if(data?.schemaVersion!==1||!Array.isArray(data.categories)||!Array.isArray(data.assets))throw Error('INVALID_CATALOG');const categories=new Set(),ids=new Set();for(const c of data.categories){if(typeof c.id!=='string'||categories.has(c.id)||!validTitle(c.title))throw Error('INVALID_CATEGORY');categories.add(c.id);}for(const a of data.assets){if(!/^[a-z0-9][a-z0-9-]*$/.test(a.id)||ids.has(a.id)||!['silhouette','photo'].includes(a.type)||!categories.has(a.categoryId)||!validTitle(a.title)||!Array.isArray(a.tags)||!a.tags.every(t=>typeof t==='string')||!publicPath(a.thumbnailUrl)||!publicPath(a.sourceUrl))throw Error('INVALID_ASSET');if(a.type==='photo'&&['sourceName','author','license','licenseUrl'].some(k=>typeof a[k]!=='string'||!a[k]))throw Error('PHOTO_PROVENANCE_REQUIRED');if(a.precomputed&&!publicPath(a.precomputed.url))throw Error('INVALID_CACHE_URL');ids.add(a.id);}return data;}
 function createRepository({load=()=>fetchJSON('/library/manifest.json')}={}){
  let catalog;async function all(){if(!catalog)catalog=Promise.resolve().then(load).then(validateManifest).catch(e=>{catalog=null;throw e;});return catalog;}
  async function getAsset(id){return (await all()).assets.find(a=>a.id===id)||null;}
  async function getCategories(type){const d=await all(),used=new Set(d.assets.filter(a=>a.type===type).map(a=>a.categoryId));return d.categories.filter(c=>used.has(c.id));}
  async function getAssets({type='silhouette',category='all',search='',page=1,lang='en'}={}){const d=await all(),q=search.trim().normalize('NFKC').toLocaleLowerCase(),names=new Map(d.categories.map(c=>[c.id,localized(c.title,lang)]));const list=d.assets.filter(a=>a.type===type&&(category==='all'||a.categoryId===category)&&(!q||[...Object.values(a.title),...a.tags,names.get(a.categoryId)].join(' ').normalize('NFKC').toLocaleLowerCase().includes(q))).sort((a,b)=>(Number(b.featured||false)-Number(a.featured||false))||((a.sortOrder||0)-(b.sortOrder||0))||a.id.localeCompare(b.id));const p=Math.max(1,Number.isInteger(page)?page:1);return {items:list.slice((p-1)*PAGE_SIZE,p*PAGE_SIZE),total:list.length,page:p,pageSize:PAGE_SIZE,hasMore:p*PAGE_SIZE<list.length};}
  return {getAsset,getAssets,getCategories};
 }
 const validPath=p=>Array.isArray(p)&&p.length>=2&&p.length<=100000&&p.every(q=>Array.isArray(q)&&q.length===2&&q.every(n=>Number.isFinite(n)&&Math.abs(n)<100000));
 function validatePrepared(bundle,{version,sourceHash,canvas,assetId}){if(typeof version!=='string'||!/^r1-r2-[a-f0-9]{64}$/.test(version)||typeof sourceHash!=='string'||!/^[a-f0-9]{64}$/.test(sourceHash)||bundle?.schemaVersion!==1||bundle.processingVersion!==version||bundle.sourceSha256!==sourceHash||bundle.assetId!==assetId||JSON.stringify(bundle.canvas)!==JSON.stringify(canvas))return null;const r=bundle.result1;if(!r||!validPath(r.contour)||!Array.isArray(r.dashes)||!r.dashes.length||!r.dashes.every(validPath)||!Array.isArray(r.internal_lines)||!r.internal_lines.every(validPath))return null;if(r.refined?.status==='ok'&&(!Array.isArray(r.refined.indices)||!r.refined.indices.every(i=>Number.isInteger(i)&&i>=0&&i<r.internal_lines.length)))return null;const o=bundle.result2;if(o){if(o.status!=='ok'||o.version!=='optimized-vector-v1'||JSON.stringify(o.canvas)!==JSON.stringify(canvas)||!validPath(o.contour)||!Array.isArray(o.internal_lines)||!o.internal_lines.every(validPath)||!Array.isArray(o.paths)||!o.paths.length||!o.paths.every(p=>validPath(p?.points))||!o.timings||typeof o.timings!=='object'||Array.isArray(o.timings)||!o.diagnostics||!Array.isArray(o.diagnostics.merged)||!Array.isArray(o.diagnostics.rejected)||![...o.diagnostics.merged,...o.diagnostics.rejected].every(p=>validPath(p?.points))||!o.paths.every(p=>p.bridges===undefined||(Array.isArray(p.bridges)&&p.bridges.every(b=>validPath(b.points)))))return null;}return bundle;}
 async function loadSource(asset,canvas){if(asset.type==='silhouette'){const data=await fetchJSON(asset.sourceUrl);if(data.schemaVersion!==1||!Array.isArray(data.polys)||!data.polys.length||!data.polys.every(p=>p.length>=3&&validPath(p)))throw Error('INVALID_SILHOUETTE');return {polys:data.polys};}
  const {bytes,type}=await fetchBytes(asset.sourceUrl,3*1024*1024);if(!['image/jpeg','image/png','image/webp'].includes(type))throw Error('INVALID_PHOTO');const file=new File([bytes],asset.id+'.'+(type==='image/jpeg'?'jpg':type.split('/')[1]),{type});let prepared=null;
  if(asset.precomputed)try{const hash=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),v=>v.toString(16).padStart(2,'0')).join('');const [bundle,versions]=await Promise.all([fetchJSON(asset.precomputed.url),fetchJSON('/library/processing-version.json')]);prepared=validatePrepared(bundle,{version:versions.processingVersion,sourceHash:hash,canvas,assetId:asset.id});if(!prepared)console.info('library_cache_fallback',{assetId:asset.id,reason:'incompatible'});}catch(error){console.info('library_cache_fallback',{assetId:asset.id,reason:error.name});}
  return {file,prepared};
 }
 const api={PAGE_SIZE,localized,publicPath,validateManifest,validatePrepared,createRepository,loadSource};root.AssetLibrary=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
