/* Developer-only hybrid experiment. Existing three production modes are frozen. */
(function(){'use strict';const H=Result3Hybrid,T=TileLayout,$=id=>document.getElementById(id);
const copy={ru:{run:'Проверить гибридную композицию',notice:'Эксперимент: результат требует визуальной проверки. Рабочие режимы сайта не изменены.',ready:'Изображение готово.',pending:'Планирование и проверка композиции…',accepted:'AI одобрил композицию. Проверьте результат визуально.',review:'Композиция требует ручной визуальной проверки.',fallback:'AI недоступен. Показана прежняя математическая раскладка.',invalid:'Не удалось обработать изображение.',AI_CONFIG_MISSING:'Серверный ключ DeepSeek не настроен.',AI_EXPERIMENT_DISABLED:'Эксперимент не включён на сервере.',AI_AUTH_ERROR:'Не удалось авторизовать сервис AI.',AI_TIMEOUT:'Превышено время ожидания AI.',AI_PLAN_INVALID:'AI вернул непригодный план.',AI_RESPONSE_INVALID:'Ответ AI не удалось прочитать.',AI_VISION_ERROR:'AI не смог принять визуальные данные.',AI_RATE_LIMIT:'Лимит запросов AI. Повторите позже.',AI_NETWORK_ERROR:'Не удалось связаться с AI.',AI_MODEL_ERROR:'Сервис AI вернул ошибку.',FALLBACK_FAILED:'Не удалось получить безопасную раскладку.'},en:{run:'Test hybrid composition',notice:'Experimental: visual review is required. Existing production modes are unchanged.',ready:'Image ready.',pending:'Planning and reviewing composition…',accepted:'AI accepted the composition. Inspect it visually.',review:'Composition needs manual visual review.',fallback:'AI unavailable. Showing the existing deterministic layout.',invalid:'Could not process this image.',AI_CONFIG_MISSING:'DeepSeek server key is not configured.',AI_EXPERIMENT_DISABLED:'The server experiment is not enabled.',AI_AUTH_ERROR:'AI service authentication failed.',AI_TIMEOUT:'AI request timed out.',AI_PLAN_INVALID:'AI returned an invalid plan.',AI_RESPONSE_INVALID:'Could not read the AI response.',AI_VISION_ERROR:'AI could not accept the visual input.',AI_RATE_LIMIT:'AI request limit reached. Try later.',AI_NETWORK_ERROR:'Could not connect to AI.',AI_MODEL_ERROR:'AI service returned an error.',FALLBACK_FAILED:'Could not produce a safe layout.'},zh:{run:'测试混合构图',notice:'实验功能：需要视觉审核。现有生产模式未更改。',ready:'图片已就绪。',pending:'正在规划和审核构图…',accepted:'AI 已批准构图。请进行视觉检查。',review:'构图需要人工视觉审核。',fallback:'AI 不可用。显示现有数学布局。',invalid:'无法处理此图片。',AI_CONFIG_MISSING:'未配置 DeepSeek 服务器密钥。',AI_EXPERIMENT_DISABLED:'服务器尚未启用实验。',AI_AUTH_ERROR:'AI 服务身份验证失败。',AI_TIMEOUT:'AI 请求超时。',AI_PLAN_INVALID:'AI 返回了无效方案。',AI_RESPONSE_INVALID:'无法读取 AI 响应。',AI_VISION_ERROR:'AI 无法接受视觉输入。',AI_RATE_LIMIT:'已达到 AI 请求限制。请稍后重试。',AI_NETWORK_ERROR:'无法连接 AI。',AI_MODEL_ERROR:'AI 服务返回错误。',FALLBACK_FAILED:'无法生成安全布局。'}};
let lang='en',file=null,answer=null,status='ready',busy=false;
// Reuse the existing locale catalog rather than another notification/i18n service.
for(const [language,entries]of Object.entries(copy))for(const [key,value]of Object.entries(entries))TileMessages[language]['hybrid.'+key]=value;
const t=k=>TileMessages[lang]['hybrid.'+k]||TileMessages[lang]['hybrid.invalid'];
function refresh(){document.documentElement.lang=lang;$('run').textContent=t('run');$('notice').textContent=t('notice');$('status').textContent=(answer?.errorCode?t('fallback')+' ':'')+t(status);$('run').disabled=busy||!file;$('upload').disabled=busy;$('format').disabled=busy;}
$('language').onchange=()=>{lang=$('language').value;refresh();};
function clear(canvas,w=400,h=400){canvas.width=w*2;canvas.height=h*2;const ctx=canvas.getContext('2d');ctx.scale(2,2);ctx.fillStyle='white';ctx.fillRect(0,0,w,h);return ctx;}
function draw(canvas,paths,layout,labels=false){const [w,h]=layout?.canvas||[400,400],ctx=clear(canvas,w,h);ctx.strokeStyle='#475569';ctx.lineWidth=.6;for(const p of paths){ctx.beginPath();p.points.forEach(([x,y],i)=>i?ctx.lineTo(x,y):ctx.moveTo(x,y));ctx.stroke();if(labels){ctx.font='4px sans-serif';ctx.fillStyle='#4338ca';ctx.fillText(p.id,p.points[0][0],p.points[0][1]);}}
if(layout)for(const tile of layout.tiles){ctx.save();ctx.translate(tile.xMm,tile.yMm);ctx.rotate(tile.angleDeg*Math.PI/180);ctx.fillStyle='#dc2626';ctx.fillRect(-15,-1.5,30,3);ctx.restore();}return canvas.toDataURL('image/jpeg',.8);}
async function load(file){const url=URL.createObjectURL(file),img=new Image();try{img.src=url;await img.decode();const scale=Math.min(1,768/Math.max(img.width,img.height)),canvas=$('source');canvas.width=Math.round(img.width*scale);canvas.height=Math.round(img.height*scale);const ctx=canvas.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(img,0,0,canvas.width,canvas.height);return canvas.toDataURL('image/jpeg',.85);}finally{URL.revokeObjectURL(url);}}
function baseline(source,canvas){return new Promise((resolve,reject)=>{const worker=new Worker('../tile-worker.js');worker.onmessage=({data})=>{worker.terminate();resolve(data.result);};worker.onerror=()=>{worker.terminate();reject(Error('FALLBACK_FAILED'));};worker.postMessage({id:1,source,options:{format:canvas[0]===canvas[1]?'40x40':'30x40',orientation:canvas[0]<canvas[1]?'portrait':'landscape'}});});}
$('upload').onchange=async()=>{file=$('upload').files[0]||null;answer=null;$('svg').disabled=$('jpg').disabled=true;status='ready';if(file&&(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>3*1024*1024)){file=null;status='invalid';}if(file)try{await load(file);}catch{file=null;status='invalid';}refresh();};
$('run').onclick=async()=>{busy=true;status='pending';answer=null;$('svg').disabled=$('jpg').disabled=true;refresh();try{
const began=performance.now(),canvas=$('format').value.split(',').map(Number),sourceImage=await load(file),original=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=reject;r.readAsDataURL(file);});
const res=await fetch('/api/contour',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:original,canvas}),signal:AbortSignal.timeout(30000)});if(!res.ok)throw Error('invalid');const detailed=await res.json(),optimized=OptimizedContour.generate(detailed,{canvas}),context=H.prepare(detailed,optimized,canvas),r2=draw($('optimized'),optimized.paths,{canvas,tiles:[]});
draw($('path-map'),context.paths.map(p=>({...p,points:p.points.map(q=>q.map((v,i)=>v*canvas[i]))})),{canvas,tiles:[]},true);
const preparedMs=performance.now()-began;let base;
const request=async(phase,payload)=>{const r=await fetch('/api/result3',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({phase,...payload}),signal:AbortSignal.timeout(45000)});let data;try{data=await r.json();}catch{throw Error('AI_RESPONSE_INVALID');}if(!r.ok)throw Object.assign(Error(data.error?.code||'AI_MODEL_ERROR'),{code:data.error?.code,contractFailure:data.error});return data;};
answer=await H.run({context,images:{source:sourceImage,result2:r2,pathMap:$('path-map').toDataURL('image/jpeg',.8),review:async layout=>draw(document.createElement('canvas'),[],layout)},request,fallback:async()=>{base=await baseline(detailed,canvas);return base;}});
draw($('target'),answer.layout.target,{canvas,tiles:[]});draw($('final'),[],answer.layout);if(!base)base=await baseline(detailed,canvas);draw($('baseline'),[],base);
$('debug').textContent=JSON.stringify({preparedMs,...answer},null,2);status=answer.errorCode?(copy[lang][answer.errorCode]?answer.errorCode:'fallback'):answer.layout.visualStatus==='AI_ACCEPTED'?'accepted':'review';$('svg').disabled=$('jpg').disabled=!H.physical(answer.layout).valid;
}catch(error){status=copy[lang][error.message]?error.message:'invalid';console.error('result3_lab_failure',{code:error.code||error.message});}finally{busy=false;refresh();}};
function download(href,name){const a=document.createElement('a');a.href=href;a.download=name;a.click();}
$('svg').onclick=()=>{if(!answer)return;const url=URL.createObjectURL(new Blob([H.exportSVG(answer.layout)],{type:'image/svg+xml'}));download(url,'result3-experiment.svg');setTimeout(()=>URL.revokeObjectURL(url),3000);};
$('jpg').onclick=()=>{if(answer)download(draw(document.createElement('canvas'),[],answer.layout),'result3-experiment.jpg');};refresh();
})();
