/* Presentation-only vocabulary, merged into the existing application i18n. */
(function(root){
  const keys=['project','results','editor','export','settings','workflow','source','detailed','optimized','physical','notStarted','ready','processing','error','parameters','newProject','dropTitle','dropHelp','choose','orPreset','replace','workspace','fit','zoomIn','zoomOut','grid','safe','width','height','large','small','total','kit','largeSource','smallSource','properties','close','preset','viewOnly','sourceHelp'];
  const values={
    ru:['Проект','Результаты','Редактор','Экспорт','Настройки','Этапы проекта','Исходное изображение','Детальный контур','Оптимизированный контур','Физическая раскладка','Не рассчитан','Готово','Обработка','Ошибка','Параметры','Новый проект','Ваше изображение — начало проекта','Перетащите фотографию или рисунок. PNG, JPG, WebP · до 3 МБ.','Выбрать изображение','Или открыть готовый силуэт','Заменить изображение','Рабочая область','Вписать','Приблизить','Отдалить','Сетка','Безопасная зона · 15 мм','Ширина','Высота','30 мм','10 мм','Всего','Набор пластин','Исходная деталь 3 × 3 см · раскладка 30 × 3 мм','Исходная деталь 1 × 3 см · раскладка 10 × 3 мм','Параметры','Закрыть','Готовый силуэт','Масштаб просмотра не меняет размеры экспорта','Выберите следующий этап слева. Исходное изображение не изменяется.'],
    en:['Project','Results','Editor','Export','Settings','Project steps','Source image','Detailed contour','Optimized contour','Physical layout','Not generated','Ready','Processing','Error','Properties','New project','Your image is the starting point','Drop a photo or drawing. PNG, JPG, WebP · up to 3 MB.','Choose image','Or open a ready-made silhouette','Replace image','Workspace','Fit','Zoom in','Zoom out','Grid','Safe area · 15 mm','Width','Height','30 mm','10 mm','Total','Piece inventory','Source piece 3 × 3 cm · layout 30 × 3 mm','Source piece 1 × 3 cm · layout 10 × 3 mm','Properties','Close','Ready-made silhouette','View zoom does not change export dimensions','Choose the next step on the left. The source image stays unchanged.'],
    zh:['项目','结果','编辑器','导出','设置','项目步骤','原始图像','详细轮廓','优化轮廓','实物排布','尚未生成','已完成','处理中','错误','参数','新建项目','从您的图像开始创作','拖入照片或绘图。PNG、JPG、WebP · 最大 3 MB。','选择图像','或打开预设轮廓','更换图像','工作区','适应画布','放大','缩小','网格','安全区域 · 15 毫米','宽度','高度','30 毫米','10 毫米','合计','板件库存','原始板件 3 × 3 厘米 · 排布 30 × 3 毫米','原始板件 1 × 3 厘米 · 排布 10 × 3 毫米','参数','关闭','预设轮廓','查看缩放不会改变导出尺寸','选择左侧的下一步骤。原始图像保持不变。']
  };
  root.WorkspaceMessages=Object.fromEntries(Object.entries(values).map(([lang,list])=>[lang,Object.fromEntries(keys.map((k,i)=>['ws.'+k,list[i]]))]));
  const status={ru:['Резервный расчёт','AI: проверено','Требует проверки','AI-планирование','Проверка композиции'],en:['Fallback layout','AI reviewed','Review needed','AI planning','Composition review'],zh:['备用排布','AI 已审核','需要审核','AI 规划中','构图审核中']};
  for(const [lang,list]of Object.entries(status))['fallback','aiApproved','aiReview','planning','qa'].forEach((k,i)=>root.WorkspaceMessages[lang]['ws.'+k]=list[i]);
  const short={ru:['Контур','Оптимизация','Раскладка'],en:['Detailed','Optimized','Layout'],zh:['详细','优化','排布']};
  for(const [lang,list]of Object.entries(short))['detailedShort','optimizedShort','physicalShort'].forEach((k,i)=>root.WorkspaceMessages[lang]['ws.'+k]=list[i]);
  for(const [lang,label]of Object.entries({ru:'Повторить обработку',en:'Retry processing',zh:'重试处理'}))root.WorkspaceMessages[lang]['ws.retry']=label;
  const projectFlow={
    ru:{createProject:'Создать новый проект',continueProject:'Продолжить текущий проект',continue:'Продолжить',uploadImage:'Загрузить своё изображение',uploadImageHelp:'Фото или рисунок · PNG, JPG, WebP',readySilhouettes:'Готовые силуэты',readySilhouettesHelp:'Выбрать форму из библиотеки',prismosaicPhotos:'Фотографии Prismosaic',prismosaicPhotosHelp:'Выбрать подготовленную фотографию',changeSource:'Изменить источник',currentSource:'Текущий источник',uploadSourceType:'Загруженное изображение',silhouetteSourceType:'Готовый силуэт',photoSourceType:'Фотография Prismosaic',cancelSourceChange:'Вернуться к текущему проекту',home:'На главную'},
    en:{createProject:'Create a new project',continueProject:'Continue current project',continue:'Continue',uploadImage:'Upload your image',uploadImageHelp:'Photo or drawing · PNG, JPG, WebP',readySilhouettes:'Ready silhouettes',readySilhouettesHelp:'Choose a shape from the library',prismosaicPhotos:'Prismosaic photos',prismosaicPhotosHelp:'Choose a curated photo',changeSource:'Change source',currentSource:'Current source',uploadSourceType:'Uploaded image',silhouetteSourceType:'Ready silhouette',photoSourceType:'Prismosaic photo',cancelSourceChange:'Return to current project',home:'Home'},
    zh:{createProject:'创建新项目',continueProject:'继续当前项目',continue:'继续',uploadImage:'上传您的图像',uploadImageHelp:'照片或绘图 · PNG、JPG、WebP',readySilhouettes:'现成轮廓',readySilhouettesHelp:'从素材库选择形状',prismosaicPhotos:'Prismosaic 照片',prismosaicPhotosHelp:'选择精选照片',changeSource:'更换来源',currentSource:'当前来源',uploadSourceType:'上传的图像',silhouetteSourceType:'现成轮廓',photoSourceType:'Prismosaic 照片',cancelSourceChange:'返回当前项目',home:'主页'}
  };
  for(const [lang,messages]of Object.entries(projectFlow))for(const [key,value]of Object.entries(messages))root.WorkspaceMessages[lang]['ws.'+key]=value;
})(globalThis);
