/* Real browser flow. Fault injection is explicitly limited to cache/catalog errors;
 * normal fallback posts to the existing local contour API. No DeepSeek success mocked. */
'use strict';
const {chromium,webkit}=require('playwright'),assert=require('node:assert/strict'),fs=require('node:fs');
const base=process.env.BASE_URL||'http://127.0.0.1:8092',engine=process.env.ENGINE==='webkit'?webkit:chromium;
(async()=>{const browser=await engine.launch({headless:true,...(engine===chromium?{executablePath:process.env.BROWSER_PATH}:{})});try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[],api=[];let workers=[];
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().includes('/api/contour'))api.push(r.url());});page.on('worker',w=>workers.push(w.url()));
 await page.addInitScript(()=>{window.libraryTestSources=0;window.addEventListener('prismosaic:view',e=>{if(e.detail.id==='source')window.libraryTestSources++;});});
 await page.goto(base+'/?lang=ru');await page.locator('#start-photos').click();await page.locator('[data-value=apple]').waitFor();
 assert.equal(await page.locator('[data-mode=photo]').getAttribute('aria-pressed'),'true');
 // Switching, title/tag search, category filtering, preserved preset dispatch.
 await page.locator('[data-mode=silhouette]').click();await page.locator('[data-value=wolf]').waitFor();
 await page.locator('[data-category=insects]').click();await page.waitForFunction(()=>document.querySelectorAll('.silhouette-card').length===3);
 await page.locator('[data-category=all]').click();await page.locator('#silhouette-search').fill('Волк');await page.waitForFunction(()=>document.querySelectorAll('.silhouette-card').length===1&&document.querySelector('.silhouette-card').dataset.value==='wolf');await page.locator('[data-value=wolf]').click();await page.locator('#silhouette-library footer button').last().click();await page.waitForFunction(()=>document.querySelector('#preset').value==='wolf');assert.equal(api.length,0);
 async function openPhotoLibrary(){await page.locator('#properties-replace').click();await page.locator('#start-photos').click();}
 async function choosePhoto(){const previous=await page.evaluate(()=>window.libraryTestSources);await openPhotoLibrary();await page.locator('[data-value=apple]').click();await page.locator('#silhouette-library footer button').last().click();await page.waitForFunction(previous=>window.libraryTestSources>previous&&document.querySelector('#step-state-1').textContent==='Готово',previous,{timeout:90000});}
 // Valid prepared R1/R2: no contour request, no optimized worker.
 await choosePhoto();assert.equal(api.length,0);workers=[];await page.locator('#result-optimized').click();await page.waitForFunction(()=>document.querySelector('#step-state-2').textContent==='Готово');assert.ok(!workers.some(u=>u.endsWith('optimized-worker.js')));
 await page.screenshot({path:'/private/tmp/library-precomputed-r2.png'});
 // Same existing Result 3 deterministic flow. Hybrid disabled by ordinary URL.
 await page.locator('#result-tiles').click();await page.waitForFunction(()=>document.querySelector('#step-state-3').textContent==='Готово',null,{timeout:90000});assert.match(await page.locator('#inventory-total-text').innerText(),/\d+ \/ 150/);
 // Missing cache: source still loads through the actual API, then ordinary R2 worker.
 await page.route('**/library/photos/apple/precomputed.json',r=>r.fulfill({status:404,body:'missing'}));await choosePhoto();assert.equal(api.length,1);workers=[];await page.locator('#result-optimized').click();await page.waitForFunction(()=>document.querySelector('#step-state-2').textContent==='Готово',null,{timeout:90000});assert.ok(workers.some(u=>u.endsWith('optimized-worker.js')));await page.unroute('**/library/photos/apple/precomputed.json');
 // Own upload stays on original path even if identical to a catalog source.
 const beforeUpload=await page.evaluate(()=>window.libraryTestSources);await page.locator('#file-input').setInputFiles('library/photos/apple/source.jpg');await page.waitForFunction(previous=>window.libraryTestSources>previous&&document.querySelector('#step-state-1').textContent==='Готово',beforeUpload,{timeout:90000});assert.equal(api.length,2);
 // Shared localization, keyboard trapping, empty search, source-load failure.
 for(const lang of ['en','zh','ru']){await page.locator('#lang').selectOption(lang);await openPhotoLibrary();await page.locator('[data-value=apple]').waitFor();assert.ok(!/lib\.|ux\./.test(await page.locator('#silhouette-library').innerText()));await page.keyboard.press('Escape');}
 await openPhotoLibrary();await page.locator('#silhouette-search').fill('nonexistentZZZ');await page.waitForFunction(()=>document.querySelector('.library-grid').textContent.includes('Ничего не найдено'));assert.equal(await page.locator('#silhouette-library footer button').last().isDisabled(),true);await page.keyboard.press('Escape');
 await page.route('**/library/photos/apple/source.jpg',r=>r.fulfill({status:404,body:'missing'}));await openPhotoLibrary();await page.locator('[data-value=apple]').click();await page.locator('#silhouette-library footer button').last().click();await page.locator('#workspace-error').waitFor({state:'visible'});assert.ok(!(await page.locator('#workspace-error').innerText()).includes('404'));await page.keyboard.press('Escape');await page.unroute('**/library/photos/apple/source.jpg');
 assert.deepEqual(errors,[]);console.log('PASS real upload and library-photo → API/R1/R2/R3, cache bypass/fallback, preset, search, categories, i18n, safe source error');await page.close();
 const faulty=await browser.newPage();let unavailable=true;await faulty.route('**/library/manifest.json',r=>unavailable?r.fulfill({status:503,body:'unavailable'}):r.continue());await faulty.route('**/library/silhouettes/wolf/thumb.svg',r=>r.fulfill({status:404,body:'missing'}));await faulty.goto(base+'/?lang=ru');await faulty.locator('#start-presets').click();await faulty.getByRole('button',{name:'Повторить',exact:true}).waitFor();unavailable=false;await faulty.getByRole('button',{name:'Повторить',exact:true}).click();await faulty.waitForFunction(()=>document.querySelector('[data-value=wolf]')?.disabled===true);await faulty.keyboard.press('Escape');assert.equal(await faulty.locator('#silhouette-library').isVisible(),false);await faulty.close();console.log('PASS unavailable catalog retry and broken-thumbnail disable');
 // Mobile large catalog is TEST-ONLY metadata, not production placeholder content.
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const catalog=JSON.parse(fs.readFileSync('library/manifest.json','utf8')),sample=catalog.assets.find(a=>a.type==='silhouette');catalog.assets=Array.from({length:500},(_,i)=>({...sample,id:'sample-'+i,title:{en:'Sample '+i,ru:'Образец '+i,zh:'示例 '+i},tags:['tag'+i]}));let originals=0;mobile.on('request',r=>{if(r.url().endsWith('/source.json'))originals++;});await mobile.route('**/library/manifest.json',r=>r.fulfill({json:catalog}));await mobile.goto(base+'/?lang=ru');await mobile.locator('#start-presets').click();await mobile.locator('.library-more').waitFor();assert.equal(await mobile.locator('.silhouette-card').count(),24);await mobile.locator('.library-more').click();await mobile.waitForFunction(()=>document.querySelectorAll('.silhouette-card').length===48);assert.equal(originals,0);
 const began=Date.now();await mobile.locator('#silhouette-search').fill('tag499');await mobile.waitForFunction(()=>document.querySelectorAll('.silhouette-card').length===1);console.log('500-asset browser search including debounce ms:',Date.now()-began);await mobile.keyboard.press('Escape');await mobile.close();
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
