'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),H=require('../result3-hybrid'),T=require('../tile-layout'),O=require('../optimized-contour'),config=require('../server/deepseek-config.cjs'),{complete}=require('../server/deepseek-client.cjs'),{messages}=require('../api/result3');
const source={contour:[[20,20],[380,20],[380,380],[20,380],[20,20]],internal_lines:[[[50,180],[180,180]],[[180,180],[300,180]]]};
const ctx=H.prepare(source,O.generate(source));
const route=(id,role,anchors)=>({id,role,priority:1,sourcePathIds:['r2_0'],source:'result2',strategy:'REROUTE',viaAnchors:anchors,reason:'clear geometry'});
const plan={version:1,objectAnalysis:'shape',essentialFeatures:['outer'],globalIntent:'intentional',complexityBudget:100,routes:[route('outer','outer',[[.1,.1],[.9,.1],[.9,.9],[.1,.9],[.1,.1]])],omissions:[]};
const qa={version:1,accept:true,recognizabilityScore:.8,silhouetteScore:.8,cleanlinessScore:.8,compositionScore:.8,repairs:[]};
const test=(name,fn)=>{fn();console.log('PASS',name);};
test('centralized model configuration and production secret reuse',()=>{assert.ok(config({}).model);assert.equal(config({DEEPSEEK_MODEL:'custom'}).model,'custom');assert.equal(config({}).enabled,false);});
test('approved production experiment and explicit kill switch',()=>{assert.equal(config({VERCEL_ENV:'production'}).enabled,true);assert.equal(config({VERCEL_ENV:'production',DEEPSEEK_RESULT3_ENABLED:'0'}).enabled,false);});
test('bounded stable planning context',()=>{H.validateContext(ctx);assert.ok(ctx.paths.every(p=>p.points.length<=24));assert.deepEqual(ctx.paths,H.prepare(source,O.generate(source)).paths);});
test('planning request contains images and numbered geometry',()=>{const image='data:image/png;base64,YQ==',m=messages({phase:'plan',context:ctx,images:{source:image,result2:image}});assert.ok(m[1].content.some(p=>p.type==='image_url'));assert.ok(JSON.stringify(m).includes('r2_0'));});
test('strict plan schema rejects arbitrary fields and unknown source IDs',()=>{assert.throws(()=>H.validatePlan({...plan,svg:'bad'},ctx));assert.throws(()=>H.validatePlan({...plan,routes:[{...plan.routes[0],sourcePathIds:['missing']}]},ctx));});
test('malformed and nonfinite geometry rejected',()=>{assert.throws(()=>H.validatePlan({...plan,routes:[route('x','outer',[[NaN,0],[2,1]])]},ctx));});
for(const strategy of ['FOLLOW_SIMPLIFIED','CUT_CORNER','BRIDGE','REROUTE','TERMINATE'])test('plan supports '+strategy,()=>{assert.equal(H.validatePlan({...plan,routes:[{...plan.routes[0],strategy}]},ctx).routes[0].strategy,strategy);});
test('restore Result 1 path',()=>{const r={...plan.routes[0],id:'restore',role:'structural',source:'result1-restored',strategy:'RESTORE',sourcePathIds:['r1_0'],viaAnchors:[]};assert.equal(H.target({...plan,routes:[...plan.routes,r]},ctx).length,2);});
test('omitted source cannot reappear in selected routes',()=>{assert.throws(()=>H.validatePlan({...plan,omissions:['r2_0']},ctx));});
test('target can deviate substantially from Result 2',()=>{const target=H.target(plan,ctx);assert.ok(T.nearestOnPath(target[0].points[0],source.contour).distance>3);});
const layout=H.follow(H.target(plan,ctx),ctx.canvas,100);
test('sequential follower exact rigid dimensions and count',()=>{assert.ok(layout.tiles.length>10&&layout.tiles.length<=100);assert.ok(layout.tiles.every(t=>t.lengthMm===30&&t.widthMm===3));});
test('SAT overlap and full rectangle safe area',()=>{assert.ok(H.physical(layout).valid);assert.ok(layout.tiles.every(t=>T.inside(t,layout.canvas)));});
test('AI cannot override physical rules',()=>{assert.equal(H.physical({...layout,tiles:[{...layout.tiles[0],lengthMm:29}]}).valid,false);assert.equal(H.physical({...layout,tiles:[layout.tiles[0],{...layout.tiles[0],id:2}]}).valid,false);});
test('export uses actual tile geometry',()=>{const svg=H.exportSVG(layout);assert.equal((svg.match(/width="30" height="3"/g)||[]).length,layout.tiles.length);});
test('hybrid uses existing editor, mounting export, undo and redo',()=>{const l={...layout,visualStatus:'AI_ACCEPTED'},doc=new T.TileDocument(l),id=l.tiles.at(-1).id;assert.ok(doc.remove(id).valid);assert.equal(doc.layout.visualStatus,'MANUALLY_EDITED');doc.undo();assert.equal(doc.layout.visualStatus,'AI_ACCEPTED');doc.redo();assert.equal(doc.layout.tiles.length,l.tiles.length-1);assert.ok(T.exportSVG(doc.layout,{mounting:true}).includes('data-tile-id'));});
test('hybrid cannot bypass export physical checks',()=>{assert.throws(()=>T.exportSVG({...layout,tiles:[{...layout.tiles[0],xMm:1}]}));assert.throws(()=>T.exportSVG({...layout,target:[{role:'outer',points:[['bad',0],[0,0]]}]}));});
test('QA schema disallows invented route and outer omission',()=>{assert.throws(()=>H.validateQA({...qa,accept:false,repairs:[{routeId:'missing',action:'OMIT',reason:''}]},plan));assert.throws(()=>H.validateQA({...qa,accept:false,repairs:[{routeId:'outer',action:'OMIT',reason:''}]},plan));});
test('local repair preserves unrelated placements',()=>{const r=route('inner','structural',[[.3,.3],[.7,.3]]),p={...plan,routes:[...plan.routes,r]},l=H.follow(H.target(p,ctx),ctx.canvas),q={...qa,accept:false,repairs:[{routeId:'inner',action:'OMIT',reason:'clutter'}]},repaired=H.repair(l,q,100);assert.deepEqual(repaired.tiles.map(t=>[t.xMm,t.yMm,t.angleDeg]),l.tiles.filter(t=>t.sourcePathId!=='inner').map(t=>[t.xMm,t.yMm,t.angleDeg]));});
test('Result 1 and Result 2 source not modified',()=>{const before=JSON.stringify(source);H.prepare(source,O.generate(source));assert.equal(JSON.stringify(source),before);});
test('new customer copy includes RU EN ZH',()=>{const js=fs.readFileSync('result3-lab.js','utf8');for(const language of ['ru:','en:','zh:'])assert.ok(js.includes(language));for(const name of ['result3-lab.js','result3-hybrid.js','api/result3.js'])new Function(fs.readFileSync(name,'utf8'));});
(async()=>{
  const response=value=>({ok:true,status:200,text:async()=>JSON.stringify({choices:[{finish_reason:'stop',message:{content:JSON.stringify(value)}}]})});
  assert.deepEqual((await complete({...config({}),apiKey:'test'},[],{fetchImpl:async()=>response(plan)})).value,plan);
  for(const [status,code] of [[401,'AI_AUTH_ERROR'],[429,'AI_RATE_LIMIT'],[400,'AI_VISION_ERROR'],[500,'AI_MODEL_ERROR']])await assert.rejects(()=>complete({...config({}),apiKey:'test'},[],{fetchImpl:async()=>({ok:false,status})}),{code});
  await assert.rejects(()=>complete({...config({}),apiKey:'test'},[],{fetchImpl:async()=>{throw Object.assign(Error(),{name:'TimeoutError'});}}),{code:'AI_TIMEOUT'});
  console.log('PASS mocked server transport, authentication, vision, rate and timeout errors');
  let calls=0;const images={source:'image',result2:'image',review:async()=> 'review'};
  const result=await H.run({context:ctx,images,request:async phase=>{calls++;return {value:phase==='plan'?plan:qa,durationMs:1};},fallback:async()=>layout});assert.equal(calls,2);assert.equal(result.layout.visualStatus,'AI_ACCEPTED');assert.equal(result.repairs,0);
  calls=0;const repaired=await H.run({context:ctx,images,request:async phase=>{calls++;return {value:phase==='plan'?plan:{...qa,accept:false,repairs:[{routeId:'outer',action:'SIMPLIFY',reason:'corner'}]}};},fallback:async()=>layout});assert.ok(calls<=2);assert.ok((repaired.repairs||0)<=1);
  const fallback=await H.run({context:ctx,images,request:async()=>{throw Error('AI_TIMEOUT');},fallback:async()=>layout});assert.equal(fallback.layout.mode,'DETERMINISTIC_FALLBACK');assert.equal(fallback.errorCode,'AI_TIMEOUT');
  console.log('PASS two-call limit, one-repair limit and safe fallback (MOCKED, not real AI)');
})().catch(error=>{console.error(error);process.exitCode=1;});
