'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),T=require('../tile-layout'),O=require('../optimized-contour'),fixtures=require('./fixtures/optimized-cases.json');
const test=(name,fn)=>{fn();console.log('PASS',name);},clone=value=>JSON.parse(JSON.stringify(value));
function layout(name='butterfly'){const source=fixtures[name],result2=O.generate(source),before=clone(result2),result3=T.generate(source,{optimizedSource:result2});assert.deepEqual(result2,before);return {source,result2,result3,expected:T.result2Routes(result2,result3.canvas).routes};}
test('Result 2 is immutable and becomes the exact transformed Result 3 rail',()=>{const {result3,expected}=layout();assert.equal(result3.targetPolicy,'IMMUTABLE_RESULT2');assert.deepEqual(result3.target.map(p=>({id:p.id,role:p.role,points:p.points})),expected.map(p=>({id:p.id,role:p.role,points:p.points})));});
test('outer contour is placed first and internal targets remain unchanged',()=>{const {result3,expected}=layout('asymmetric'),firstInternal=result3.tiles.findIndex(t=>t.role!=='outer'),lastOuter=result3.tiles.map(t=>t.role).lastIndexOf('outer');assert.ok(firstInternal<0||firstInternal>lastOuter);assert.deepEqual(result3.target.slice(1).map(p=>p.points),expected.slice(1).map(p=>p.points));});
test('mixed look-ahead considers both sizes; straight prefers large and bend can select small',()=>{const straight=T.followMixed([{id:'straight',role:'outer',priority:1,points:[[40,40],[340,40]]}],[400,400]),bend=T.followMixed([{id:'bend',role:'outer',priority:1,points:[[40,40],[135,40],[150,55],[150,200]]}],[400,400]);assert.equal(straight.inventory.smallUsed,0);assert.ok(straight.inventory.largeUsed>0);assert.ok(bend.inventory.smallUsed>0);for(const result of [straight,bend])assert.ok(result.mixedDiagnostics.largeCandidatesGenerated>0&&result.mixedDiagnostics.smallCandidatesGenerated>0);});
test('Result 3 never creates, removes or redraws a Result 2 target path',()=>{for(const name of ['butterfly','bat','asymmetric']){const {result3,expected}=layout(name);assert.deepEqual(result3.target.map(p=>p.id),expected.map(p=>p.id));assert.deepEqual(result3.target.map(p=>p.points),expected.map(p=>p.points));assert.ok(T.inventory(result3.tiles).valid);}});
test('butterfly retains the Result 2 silhouette with measurable rail diagnostics',()=>{const {result3}=layout();assert.ok(result3.metrics.outerCoveragePercent>=85);assert.ok(result3.metrics.meanDistanceToResult2<=3);assert.ok(result3.metrics.largeUsed>0&&result3.metrics.smallUsed>0);assert.ok(result3.metrics.largeUsed<=100&&result3.metrics.smallUsed<=50&&result3.metrics.totalUsed<=150);});
test('internal paths are attempted by Result 2 importance after the outer rail',()=>{const result2={status:'ok',paths:[{id:'outer',role:'outer',points:[[20,20],[380,20],[380,380],[20,380],[20,20]]},{id:'low',role:'internal',importance:.1,points:[[70,100],[330,100]]},{id:'high',role:'internal',importance:.9,points:[[70,300],[330,300]]}],contour:[[20,20],[380,20],[380,380],[20,380],[20,20]],internal_lines:[[[70,100],[330,100]],[[70,300],[330,300]]]},result=T.generate(result2,{optimizedSource:result2}),skeleton=result.tiles.filter(t=>t.role==='skeleton');assert.ok(skeleton.length);assert.equal(skeleton[0].sourcePathId,'high');assert.deepEqual(result.target.map(p=>p.id),['outer','low','high']);});
test('both active workers use the same direct Result 2 solver without AI geometry planning',()=>{const normal=fs.readFileSync('tile-worker.js','utf8'),experimental=fs.readFileSync('result3-worker.js','utf8');for(const source of [normal,experimental]){assert.match(source,/optimizedSource:optimized/);assert.doesNotMatch(source,/Result3Hybrid\.run|\/api\/result3/);}assert.match(experimental,/aiGeometryPlanning:false/);});
